baseURL = 'https://satoshicano.dev/'
languageCode = 'ja-jp'
title = "satoshicano's Blog"

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[params]
  # color style
  color = 'linen' # linen, wheat, gray, light

  # header social icons
  twitter = 'satoshicano'
  github = 'satoshicano'
  instagram = 'satoshicano'

  # home page profile
  avatar = 'satoshicano@gmail.com'            # gravatar email or image url
  name = 'satoshicano'
  bio = 'Software engineer working in Japan.'


  # misc
  disableHLJS = true                                  # disable highlight.js
  disablePostNavigation = true                        # disable post navigation
  monoDarkIcon = true                                 # show monochrome dark mode icon
  math = true                                         # enable KaTeX math typesetting globally
  localKatex = false                                  # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                             # customize the default favicon
